export enum companyActionTypes {
    GET_COMPANIES = 'GET_COMPANIES',
    GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS',
    GET_COMPANIES_ERROR = 'GET_COMPANIES_ERROR',
}

export enum itemActionTypes {
    GET_ITEMS = 'GET_ITEMS',
    GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS',
    GET_ITEMS_ERROR = 'GET_ITEMS_ERROR',
}
